# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b5b2535f97915673698f5fb11b0d40b2be9666667ba89be8242ca71bea32700003ae2f8a9462ddce6e6e1ab8cfda9bffa16956e040bac9e48e93a5eca5730db

test:
  secret_key_base: f18deeff0c260afc3a095adb7a6618fc90d8db185625f77e1f9b1f73a0f6dd80e2108d88b6fac4179c334d6393364338236b28616a3d3dc4510d3e207be5c481

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
